spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  profiles:
    active: dev

logging:
  level:
    root: info
    com.com.project.Lapstore: debug
    org.hibernate.SQL: debug
    #  org.hibernate.type: trace

info:
  app:
    name: LapStore
    description: "노트북 가격비교 웹 어플리케이션입니다."
    version: "1.0.0"

jwt:
  secret: myungjiuniversitylapstoredevjsonwebtokensecretkey202403
  token-validity-in-seconds: 864000
