spring:
  datasource:
    url: jdbc:mysql://localhost:3306/labstoreDB?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 110811
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    root: info
    com.com.project.Lapstore: debug

server:
  port: 8081

info:
  app:
    name: LapStore
    description: "노트북 가격비교 웹 어플리케이션입니다."
    version: "1.0.0"
