spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lap_store_dev?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 110811
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
    defer-datasource-initialization: true

logging:
  level:
    root: info
    com.com.project.Lapstore: debug
    org.hibernate.SQL: debug
    #  org.hibernate.type: trace

info:
  app:
    name: LapStore
    description: "노트북 가격비교 웹 어플리케이션입니다."
    version: "1.0.0"

jwt:
  secret: myungjiuniversitylapstoredevjsonwebtokensecretkey202403
  token-validity-in-seconds: 864000
